services:
  streamlit_ui:
    restart: always
    container_name: oasis_st_ui
    build:
      dockerfile: ./oasisui_st_app.Dockerfile
    ports:
      - 8501:8501
    environment:
      - API_URL=http://server:8000
    develop:
      watch:
        - action: sync
          path: ./app.py
          target: ./usr/src/app/app.py
        - action: sync
          path: ./pages/
          target: ./usr/src/app/pages/
        - action: sync
          path: ./modules/
          target: ./usr/src/app/modules/
        - action: sync
          path: ./ui-config.json
          target: ./usr/src/app/ui-config.json
        - action: sync
          path: ./defaults/
          target: ./usr/src/app/defaults/

# networks:
#   platform_network:
#     name: oasisstui_default
#     external: true
