volumes:
  server-db-OasisData:
  celery-db-OasisData:
  filestore-OasisData:
x-shared-env: &shared-env
  OASIS_DEBUG: 1
  OASIS_URL_SUB_PATH: 0
  OASIS_CELERY_BROKER_URL: "amqp://rabbit:rabbit@broker:5672"
  OASIS_SERVER_DB_HOST: server-db
  OASIS_SERVER_DB_PASS: oasis
  OASIS_SERVER_DB_USER: oasis
  OASIS_SERVER_DB_NAME: oasis
  OASIS_SERVER_DB_PORT: 5432
  OASIS_SERVER_CHANNEL_LAYER_HOST: channel-layer
  OASIS_SERVER_DB_ENGINE: django.db.backends.postgresql_psycopg2
  OASIS_CELERY_DB_ENGINE: db+postgresql+psycopg2
  OASIS_CELERY_DB_HOST: celery-db
  OASIS_CELERY_DB_PASS: password
  OASIS_CELERY_DB_USER: celery
  OASIS_CELERY_DB_NAME: celery
  OASIS_CELERY_DB_PORT: 5432
  OASIS_INPUT_GENERATION_CONTROLLER_QUEUE: task-controller
  OASIS_LOSSES_GENERATION_CONTROLLER_QUEUE: task-controller

x-volumes: &shared-volumes
  - filestore-OasisData:/shared-fs:rw
services:
  server:
   restart: always
   image: ${SERVER_IMG:-coreoasis/api_server}:${VERS_API:-latest}
   command: ["./wsgi/run-wsgi.sh"]
   ports:
     - 8000:8000
     - 51970:51970
   links:
     - server-db
     - celery-db
     - broker
   environment:
     <<: *shared-env
     STARTUP_RUN_MIGRATIONS: "true"
     OASIS_ADMIN_USER: admin
     OASIS_ADMIN_PASS: catmodels
   volumes:
     - filestore-OasisData:/shared-fs:rw
   healthcheck:
      test: curl --fail http:localhost:8000/healthcheck/ || exit
      interval: 30s
      retries : 10
      start_period: 30s
      timeout: 10s
  server_websocket:
   restart: always
   image: ${SERVER_IMG:-coreoasis/api_server}:${VERS_API:-latest}
   command: ["./asgi/run-asgi.sh"]
   links:
     - server-db
     - celery-db
     - broker
   ports:
     - 8001:8001
   environment:
     <<: *shared-env
   volumes:
     - filestore-OasisData:/shared-fs:rw
  v2-worker-monitor:
   restart: always
   image: ${SERVER_IMG:-coreoasis/api_server}:${VERS_API:-latest}
   command: [celery, -A, 'src.server.oasisapi.celery_app_v2', worker, --loglevel=INFO,  -Q, celery-v2]
   links:
     - server-db
     - celery-db
     - broker
   environment:
     <<: *shared-env
   volumes:
     - filestore-OasisData:/shared-fs:rw
  v2-task-controller:
   restart: always
   image: ${SERVER_IMG:-coreoasis/api_server}:${VERS_API:-latest}
   command: [celery, -A, 'src.server.oasisapi.celery_app_v2', worker, --loglevel=INFO, -Q, task-controller]
   links:
     - server-db
     - celery-db
     - broker
   environment:
     <<: *shared-env
   volumes:
     - filestore-OasisData:/shared-fs:rw
  celery-beat_v2:
   restart: always
   image: ${SERVER_IMG:-coreoasis/api_server}:${VERS_API:-latest}
   command: [celery, -A, src.server.oasisapi.celery_app_v2, beat, --loglevel=INFO]
   links:
     - server-db
     - celery-db
     - broker
   environment:
     <<: *shared-env
   volumes: *shared-volumes
  piwind-worker:
    restart: always
    image: ${WORKER_IMG:-coreoasis/model_worker}:${VERS_WORKER:-latest}
    build:
      context: .
      dockerfile: Dockerfile.model_worker
    links:
     - celery-db
     - broker:mybroker
    environment:
     <<: *shared-env
     OASIS_MODEL_SUPPLIER_ID: OasisLMF
     OASIS_MODEL_ID: PiWind
     OASIS_MODEL_VERSION_ID: 'v2'
     OASIS_RUN_MODE: v2
    volumes:
     - ./OasisPiWind/:/home/worker/model
     - filestore-OasisData:/shared-fs:rw
  maeq-worker:
    restart: always
    image: ${WORKER_IMG:-coreoasis/model_worker}:${VERS_WORKER:-latest}
    build:
      context: .
      dockerfile: Dockerfile.model_worker
    links:
      - celery-db
      - broker:mybroker
    environment:
      <<: *shared-env
      OASIS_MODEL_SUPPLIER_ID: Impact Forecasting
      OASIS_MODEL_ID: MAEQ
      OASIS_MODEL_VERSION_ID: 'v2'
      OASIS_RUN_MODE: v2
    volumes:
      - filestore-OasisData:/shared-fs:rw
      - ${SCENARIOS_PATH}/ImpactForecasting/MAEQ/1.0.0/:/home/worker/model
  euws-worker:
    restart: always
    image: ${WORKER_IMG:-coreoasis/model_worker}:${VERS_WORKER:-latest}
    build:
      context: .
      dockerfile: Dockerfile.model_worker
    links:
      - celery-db
      - broker:mybroker
    environment:
      <<: *shared-env
      OASIS_MODEL_SUPPLIER_ID: Impact Forecasting
      OASIS_MODEL_ID: EUWS
      OASIS_MODEL_VERSION_ID: 'v2'
      OASIS_RUN_MODE: v2
    volumes:
      - filestore-OasisData:/shared-fs:rw
      - ${SCENARIOS_PATH}/ImpactForecasting/EUWS/1.0.0/:/home/worker/model
  treq-worker:
    restart: always
    image: ${WORKER_IMG:-coreoasis/model_worker}:${VERS_WORKER:-latest}
    build:
      context: .
      dockerfile: Dockerfile.model_worker
    links:
      - celery-db
      - broker:mybroker
    environment:
      <<: *shared-env
      OASIS_MODEL_SUPPLIER_ID: Impact Forecasting
      OASIS_MODEL_ID: TREQ
      OASIS_MODEL_VERSION_ID: 'v2'
      OASIS_RUN_MODE: v2
    volumes:
      - filestore-OasisData:/shared-fs:rw
      - ${SCENARIOS_PATH}/ImpactForecasting/TREQ/1.0.0/:/home/worker/model
  philippines_taiwan_defended-worker:
    restart: always
    image: ${WORKER_IMG:-coreoasis/model_worker}:${VERS_WORKER:-latest}
    build:
      context: .
      dockerfile: Dockerfile.model_worker
    links:
     - celery-db
     - broker:mybroker
    environment:
     <<: *shared-env
     OASIS_MODEL_SUPPLIER_ID: JBA
     OASIS_MODEL_ID: Philippines-Taiwan-Defended
     OASIS_MODEL_VERSION_ID: 'v2'
     OASIS_RUN_MODE: v2
     OASIS_OASISLMF_CONFIG: /home/worker/model/oasislmf.json
    volumes:
     - ${SCENARIOS_PATH}/JBA/Philippines-Taiwan/combined-defended/:/home/worker/model
     - filestore-OasisData:/shared-fs:rw
  philippines_taiwan_undefended-worker:
    restart: always
    image: ${WORKER_IMG:-coreoasis/model_worker}:${VERS_WORKER:-latest}
    build:
      context: .
      dockerfile: Dockerfile.model_worker
    links:
     - celery-db
     - broker:mybroker
    environment:
     <<: *shared-env
     OASIS_MODEL_SUPPLIER_ID: JBA
     OASIS_MODEL_ID: Philippines-Taiwan-Undefended
     OASIS_MODEL_VERSION_ID: 'v2'
     OASIS_RUN_MODE: v2
     OASIS_OASISLMF_CONFIG: /home/worker/model/oasislmf.json
    volumes:
     - ${SCENARIOS_PATH}/JBA/Philippines-Taiwan/combined-undefended/:/home/worker/model
     - filestore-OasisData:/shared-fs:rw
  ghana-E635900-worker:
    restart: always
    image: ${WORKER_IMG:-coreoasis/model_worker}:${VERS_WORKER:-latest}
    build:
      context: .
      dockerfile: Dockerfile.model_worker
    links:
     - celery-db
     - broker:mybroker
    environment:
     <<: *shared-env
     OASIS_MODEL_SUPPLIER_ID: JBA
     OASIS_MODEL_ID: Ghana-E635900
     OASIS_MODEL_VERSION_ID: 'v2'
     OASIS_RUN_MODE: v2
     OASIS_OASISLMF_CONFIG: /home/worker/model/oasislmf.json
    volumes:
     - ${SCENARIOS_PATH}/JBA/Ghana/E635900/combined/:/home/worker/model
     - filestore-OasisData:/shared-fs:rw
  ghana-E689982-worker:
    restart: always
    image: ${WORKER_IMG:-coreoasis/model_worker}:${VERS_WORKER:-latest}
    build:
      context: .
      dockerfile: Dockerfile.model_worker
    links:
     - celery-db
     - broker:mybroker
    environment:
     <<: *shared-env
     OASIS_MODEL_SUPPLIER_ID: JBA
     OASIS_MODEL_ID: Ghana-E689982
     OASIS_MODEL_VERSION_ID: 'v2'
     OASIS_RUN_MODE: v2
     OASIS_OASISLMF_CONFIG: /home/worker/model/oasislmf.json
    volumes:
     - ${SCENARIOS_PATH}/JBA/Ghana/E689982/combined/:/home/worker/model
     - filestore-OasisData:/shared-fs:rw
  ghana-E760461-worker:
    restart: always
    image: ${WORKER_IMG:-coreoasis/model_worker}:${VERS_WORKER:-latest}
    build:
      context: .
      dockerfile: Dockerfile.model_worker
    links:
     - celery-db
     - broker:mybroker
    environment:
     <<: *shared-env
     OASIS_MODEL_SUPPLIER_ID: JBA
     OASIS_MODEL_ID: Ghana-E760461
     OASIS_MODEL_VERSION_ID: 'v2'
     OASIS_RUN_MODE: v2
     OASIS_OASISLMF_CONFIG: /home/worker/model/oasislmf.json
    volumes:
     - ${SCENARIOS_PATH}/JBA/Ghana/E760461/combined/:/home/worker/model
     - filestore-OasisData:/shared-fs:rw
  nepal-E151185-worker:
    restart: always
    image: ${WORKER_IMG:-coreoasis/model_worker}:${VERS_WORKER:-latest}
    build:
      context: .
      dockerfile: Dockerfile.model_worker
    links:
     - celery-db
     - broker:mybroker
    environment:
     <<: *shared-env
     OASIS_MODEL_SUPPLIER_ID: JBA
     OASIS_MODEL_ID: Nepal-E151185
     OASIS_MODEL_VERSION_ID: 'v2'
     OASIS_RUN_MODE: v2
     OASIS_OASISLMF_CONFIG: /home/worker/model/oasislmf.json
    volumes:
     - ${SCENARIOS_PATH}/JBA/Nepal/E151185/combined/:/home/worker/model
     - filestore-OasisData:/shared-fs:rw
  nepal-E432557-worker:
    restart: always
    image: ${WORKER_IMG:-coreoasis/model_worker}:${VERS_WORKER:-latest}
    build:
      context: .
      dockerfile: Dockerfile.model_worker
    links:
     - celery-db
     - broker:mybroker
    environment:
     <<: *shared-env
     OASIS_MODEL_SUPPLIER_ID: JBA
     OASIS_MODEL_ID: Nepal-E432557
     OASIS_MODEL_VERSION_ID: 'v2'
     OASIS_RUN_MODE: v2
     OASIS_OASISLMF_CONFIG: /home/worker/model/oasislmf.json
    volumes:
     - ${SCENARIOS_PATH}/JBA/Nepal/E432557/combined/:/home/worker/model
     - filestore-OasisData:/shared-fs:rw
  nepal-E505423-worker:
    restart: always
    image: ${WORKER_IMG:-coreoasis/model_worker}:${VERS_WORKER:-latest}
    build:
      context: .
      dockerfile: Dockerfile.model_worker
    links:
     - celery-db
     - broker:mybroker
    environment:
     <<: *shared-env
     OASIS_MODEL_SUPPLIER_ID: JBA
     OASIS_MODEL_ID: Nepal-E505423
     OASIS_MODEL_VERSION_ID: 'v2'
     OASIS_RUN_MODE: v2
     OASIS_OASISLMF_CONFIG: /home/worker/model/oasislmf.json
    volumes:
     - ${SCENARIOS_PATH}/JBA/Nepal/E505423/combined/:/home/worker/model
     - filestore-OasisData:/shared-fs:rw
  us_hurricane-worker:
    restart: always
    image: ${WORKER_IMG:-coreoasis/model_worker}:${VERS_WORKER:-latest}
    build:
      context: .
      dockerfile: Dockerfile.model_worker
    links:
     - celery-db
     - broker:mybroker
    environment:
     <<: *shared-env
     OASIS_MODEL_SUPPLIER_ID: ARA
     OASIS_MODEL_ID: US-Hurricane
     OASIS_MODEL_VERSION_ID: 'v2'
     OASIS_RUN_MODE: v2
     OASIS_OASISLMF_CONFIG: /home/worker/model/oasislmf.json
    volumes:
     - ${SCENARIOS_PATH}/ARA/US_Hurricane/:/home/worker/model
     - filestore-OasisData:/shared-fs:rw
  france_hail-worker:
    restart: always
    image: ${WORKER_IMG:-coreoasis/model_worker}:${VERS_WORKER:-latest}
    build:
      context: .
      dockerfile: Dockerfile.model_worker
    links:
     - celery-db
     - broker:mybroker
    environment:
     <<: *shared-env
     OASIS_MODEL_SUPPLIER_ID: IPE
     OASIS_MODEL_ID: France-Hail
     OASIS_MODEL_VERSION_ID: 'v2'
     OASIS_RUN_MODE: v2
     OASIS_OASISLMF_CONFIG: /home/worker/model/oasislmf.json
    volumes:
     - ${SCENARIOS_PATH}/IPE/FranceHail/:/home/worker/model
     - filestore-OasisData:/shared-fs:rw
  server-db:
    restart: always
    image: postgres
    environment:
      - POSTGRES_DB=oasis
      - POSTGRES_USER=oasis
      - POSTGRES_PASSWORD=oasis
    volumes:
      - server-db-OasisData:/var/lib/postgresql/data:rw
    ports:
      - 33307:3306
  celery-db:
    restart: always
    image: postgres
    environment:
      - POSTGRES_DB=celery
      - POSTGRES_USER=celery
      - POSTGRES_PASSWORD=password
    volumes:
      - celery-db-OasisData:/var/lib/postgresql/data:rw
    ports:
      - 33306:5432
  broker:
    restart: always
    image: rabbitmq:3.8.14-management
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabbit
    ports:
      - 5672:5672
      - 15672:15672
  channel-layer:
    restart: always
    image: redis:5.0.7
    ports:
      - 6379:6379
