name: Docker Scenarios UI CD
on:
  workflow_dispatch:
    inputs:
      deploy-ui:
        required: true
        default: 'false'
        type: string
      deploy-all:
        required: true
        default: 'false'
        type: string
      wipe:
        required: true
        default: 'false'
        type: string
      update-scenarios:
        required: true
        default: 'false'
        type: string

env:
  DEPLOY_UI: 'false'
  DEPLOY_ALL: 'false'
  UPDATE_SCENARIOS: 'false'
  WIPE: 'false'
  UI_PATH: ${{ vars.UI_PATH }}
  MODELS_PATH: ${{ vars.MODELS_PATH }}

jobs:
  deploy:
    name: Testing
    runs-on: ubuntu-latest
    steps:
    - name: Set inputs
      run: |
         [[ -z "${{ inputs.deploy-ui }}" ]] || echo "DEPLOY_UI=${{ inputs.deploy-ui }}" >> $GITHUB_ENV
         [[ -z "${{ inputs.deploy-all }}" ]] || echo "DEPLOY_ALL=${{ inputs.deploy-all }}" >> $GITHUB_ENV
         [[ -z "${{ inputs.wipe }}" ]] || echo "WIPE=${{ inputs.wipe }}" >> $GITHUB_ENV
         [[ -z "${{ inputs.update-scenarios }}" ]] || echo "UPDATE_SCENARIOS=${{ inputs.update-scenarios }}" >> $GITHUB_ENV
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Execute remote SSH commands using password
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.SCENARIOS_HOST }}
        username: ${{ vars.SCENARIOS_USER }}
        key: ${{ secrets.SCENARIOS_KEY }}
        proxy_host: ${{ secrets.PROXY_HOST }}
        proxy_username: ${{ secrets.PROXY_USERNAME }}
        proxy_key: ${{ secrets.SCENARIOS_KEY }}
        envs: DEPLOY_UI, UI_PATH, DEPLOY_ALL, WIPE, MODELS_PATH, UPDATE_SCENARIOS
        script_path: scenarios/deploy_scenarios_ui.sh
