name: Docker Scenarios UI CD
on:
  workflow_dispatch:
    inputs:
      deploy-ui:
        required: true
        default: 'false'
        type: string

env:
  DEPLOY_UI: 'false'
  UI_PATH: ./OasisPythonUI

jobs:
  deploy:
    name: Testing
    runs-on: ubuntu-latest
    steps:
    - name: Set inputs
      run: |
         [[ -z "${{ inputs.deploy-ui }}" ]] || echo "DEPLOY_UI=${{ inputs.deploy-ui }}" >> $GITHUB_ENV
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Execute remote SSH commands using password
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.SCENARIOS_HOST }}
        username: ${{ vars.SCENARIOS_USER }}
        key: ${{ secrets.SCENARIOS_KEY }}
        proxy_host: ${{ secrets.PROXY_HOST }}
        proxy_username: ${{ secrets.PROXY_USERNAME }}
        proxy_key: ${{ secrets.SCENARIOS_KEY }}
        envs: DEPLOY_UI, UI_PATH
        script_path: scenarios/deploy_scenarios_ui.sh
